### ISSUE TITLE
when use PayUMoney test mode get error "Sorry, Some Problem Occurred"

### ISSUE THREAD

**Issue by bhavingajjar** [softon/indipay#45]
test url for payUmoney is https://sandboxsecure.payu.in/_payment
in package i found https://test.payu.in/_payment
 when i change the url because of i am using with composer so not able to change directly in package

**Comment by softon** [comment]
sorry for the late reply. was caught up in some projects. is it working with the new test url. as when the package was created https://test.payu.in/_payment was the the test url. if it does work with the new url just make a PR i will merge it after reviewing. Thank you.

**Comment by aimflaiims** [comment]
The Key and salt provided by payumoney is invalid use the following for testing:

// Merchant key here as provided by Payu
$MERCHANT_KEY = "gtKFFx";

// Merchant Salt as provided by Payu
$SALT = "eCwWELxi";
And make sure to leave service provider field blank.

**Comment by akgarg007** [comment]
Your payumoney account is not working.

Reason - Not activated.

Once you register with PayUmoney website, you get your credentials immediately. Wait! You have credentials but  your account is not activated.

Recently PayUMoney has changed their process. This is for both production and sandbox. To start with website integration, you need an active account. So get your account activated. After that you can start integration. This is due to spammers and fake users. Spammers are always bad. To stop bad practices, they follow legal process.

PayUmoney sends legal agreement paper at your business address. Please sign the agreement. Once it is signed, send it back to PayUMoney. Once they receive signed agreement, they approve your account. They will activate your test account in a day or two. Please take help of their customer support to understand it.

Once your account is active, you can test your integration code. It will work. You can start receiving payments as well.

In case you have made above two mistakes, please correct them.
